### ISSUE TITLE
`NonBlocking` doesn't implement `Send` and `Sync`

### ISSUE THREAD

**Issue by parazyd** [smol-rs/event-listener#113] opened 2024-01-09 14:54 UTC
Hi.

In https://docs.rs/event-listener-strategy/latest/event_listener_strategy/struct.NonBlocking.html there are
auto-trait implementations of `!Send` and `!Sync`. Is this now the intended behaviour?

This causes an issue for using `async_lock::OnceCell` between threads. It used to work before `smol-2.0.0` was released.

**Comment by parazyd** [comment] 2024-01-09 14:55
When compiling my code, I get the following errors:

```
error[E0277]: `*mut ()` cannot be sent between threads safely
   --> src/net/session/manual_session.rs:87:13
    |
86  |         task.clone().start(
    |                      ----- required by a bound introduced by this call
87  |             self.clone().channel_connect_loop(addr),
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `*mut ()` cannot be sent between threads safely
...
98  |     pub async fn channel_connect_loop(self: Arc<Self>, addr: Url) -> Result<()> {
    |     --------------------------------------------------------------------------- within this `impl futures::Future<Output = std::result::Result<(), error::Error>>`
    |
    = help: within `impl futures::Future<Output = std::result::Result<(), error::Error>>`, the trait `std::marker::Send` is not implemented for `*mut ()`
note: required because it appears within the type `std::marker::PhantomData<*mut ()>`
   --> /rustc/75c68cfd2b9870f2953b62d250bd7d0564a7b56d/library/core/src/marker.rs:809:12
note: required because it appears within the type `std::task::Context<'_>`
   --> /rustc/75c68cfd2b9870f2953b62d250bd7d0564a7b56d/library/core/src/task/wake.rs:179:12
note: required because it appears within the type `std::marker::PhantomData<std::task::Context<'_>>`
   --> /rustc/75c68cfd2b9870f2953b62d250bd7d0564a7b56d/library/core/src/marker.rs:809:12
note: required because it appears within the type `event_listener_strategy::NonBlocking<'_>`
   --> /home/parazyd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/event-listener-strategy-0.4.0/src/lib.rs:442:12
    |
442 | pub struct NonBlocking<'a> {
    |            ^^^^^^^^^^^
    = note: required because it captures the following types: `&smol::async_lock::OnceCell<arti_client::TorClient<tor_rtcompat::PreferredRuntime>>`, `event_listener_strategy::NonBlocking<'_>`, `impl futures::Future<Output = std::result::Result<(), arti_client::Error>>`
note: required because it's used within this `async` fn body
   --> /home/parazyd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-lock-3.2.0/src/once_cell.rs:379:24
    |
379 |       ) -> Result<&T, E> {
    |  ________________________^
380 | |         // Fast path: see if the value is already initialized.
381 | |         if let Some(value) = self.get() {
382 | |             return Ok(value);
...   |
392 | |         Ok(unsafe { self.get_unchecked() })
393 | |     }
    | |_____^
    = note: required because it captures the following types: `&str`, `u16`, `std::option::Option<std::time::Duration>`, `impl futures::Future<Output = std::result::Result<&arti_client::TorClient<tor_rtcompat::PreferredRuntime>, arti_client::Error>>`, `arti_client::StreamPrefs`, `impl futures::Future<Output = std::result::Result<std::result::Result<arti_client::DataStream, arti_client::Error>, system::timeout::TimeoutError>>`, `impl futures::Future<Output = std::result::Result<arti_client::DataStream, arti_client::Error>>`
note: required because it's used within this `async` fn body
   --> src/net/transport/tor.rs:47:29
    |
47  |       ) -> Result<DataStream> {
    |  _____________________________^
48  | |         debug!(target: "net::tor::do_dial", "Dialing {}:{} with Tor...", host, port);
49  | |
50  | |         // Initialize or fetch the static TOR_CLIENT that should be reused in
...   |
68  | |         Ok(stream?)
69  | |     }
    | |_____^
    = note: required because it captures the following types: `std::vec::Vec<std::net::SocketAddr>`, `impl futures::Future<Output = std::result::Result<smol::async_net::TcpStream, error::Error>>`, `std::vec::Vec<std::net::SocketAddr>`, `impl futures::Future<Output = std::result::Result<smol::async_net::TcpStream, error::Error>>`, `impl futures::Future<Output = std::result::Result<async_rustls::TlsStream<smol::async_net::TcpStream>, error::Error>>`, `impl futures::Future<Output = std::result::Result<arti_client::DataStream, error::Error>>`, `impl futures::Future<Output = std::result::Result<arti_client::DataStream, error::Error>>`, `impl futures::Future<Output = std::result::Result<async_rustls::TlsStream<arti_client::DataStream>, error::Error>>`, `impl futures::Future<Output = std::result::Result<smol::async_net::unix::UnixStream, error::Error>>`
note: required because it's used within this `async` fn body
   --> src/net/transport/mod.rs:201:86
    |
201 |       pub async fn dial(&self, timeout: Option<Duration>) -> Result<Box<dyn PtStream>> {
    |  ______________________________________________________________________________________^
202 | |         match &self.variant {
203 | |             #[cfg(feature = "p2p-tcp")]
204 | |             DialerVariant::Tcp(dialer) => {
...   |
284 | |         }
285 | |     }
    | |_____^
    = note: required because it captures the following types: `&net::connector::Connector`, `&url::Url`, `std::sync::Arc<net::hosts::Hosts>`, `std::sync::Arc<net::p2p::P2p>`, `std::sync::Arc<dyn net::session::Session + std::marker::Send + std::marker::Sync>`, `impl futures::Future<Output = bool>`, `url::Url`, `&str`, `net::transport::Dialer`, `impl futures::Future<Output = std::result::Result<net::transport::Dialer, error::Error>>`, `impl futures::Future<Output = std::result::Result<std::boxed::Box<(dyn net::transport::PtStream + 'static)>, error::Error>>`, `impl futures::Future<Output = std::sync::Arc<net::channel::Channel>>`
note: required because it's used within this `async` fn body
   --> src/net/connector.rs:47:73
    |
47  |       pub async fn connect(&self, url: &Url) -> Result<(Url, ChannelPtr)> {
    |  _________________________________________________________________________^
48  | |         if self.session.upgrade().unwrap().p2p().hosts().is_rejected(url).await {
49  | |             debug!(target: "net::connector::connect", "Peer {} is rejected", url);
50  | |             return Err(Error::ConnectFailed)
...   |
74  | |         Ok((endpoint, channel))
75  | |     }
    | |_____^
    = note: required because it captures the following types: `std::sync::Arc<net::session::manual_session::ManualSession>`, `url::Url`, `std::sync::Arc<smol::Executor<'_>>`, `std::sync::Arc<net::settings::Settings>`, `net::connector::Connector`, `usize`, `usize`, `std::sync::Arc<net::p2p::P2p>`, `impl futures::Future<Output = bool>`, `i32`, `std::result::Result<(url::Url, std::sync::Arc<net::channel::Channel>), error::Error>`, `impl futures::Future<Output = std::result::Result<(url::Url, std::sync::Arc<net::channel::Channel>), error::Error>>`, `url::Url`, `std::sync::Arc<net::channel::Channel>`, `system::subscriber::Subscription<error::Error>`, `impl futures::Future<Output = std::result::Result<system::subscriber::Subscription<error::Error>, error::Error>>`, `std::pin::Pin<std::boxed::Box<dyn futures::Future<Output = std::result::Result<(), error::Error>> + std::marker::Send>>`, `std::sync::Arc<net::p2p::P2p>`, `impl futures::Future<Output = ()>`, `impl futures::Future<Output = ()>`, `impl futures::Future<Output = error::Error>`, `impl futures::Future<Output = ()>`, `impl futures::Future<Output = ()>`, `std::sync::Arc<net::p2p::P2p>`, `impl futures::Future<Output = ()>`
note: required because it's used within this `async` fn body
   --> src/net/session/manual_session.rs:98:81
    |
98  |       pub async fn channel_connect_loop(self: Arc<Self>, addr: Url) -> Result<()> {
    |  _________________________________________________________________________________^
99  | |         let ex = self.p2p().executor();
100 | |         let parent = Arc::downgrade(&self);
101 | |         let settings = self.p2p().settings();
...   |
183 | |         Ok(())
184 | |     }
    | |_____^
note: required by a bound in `system::stoppable_task::StoppableTask::start`
   --> src/system/stoppable_task.rs:72:68
    |
65  |     pub fn start<'a, MainFut, StopFut, StopFn, Error>(
    |            ----- required by a bound in this associated function
...
72  |         MainFut: Future<Output = std::result::Result<(), Error>> + Send + 'a,
    |                                                                    ^^^^ required by this bound in `StoppableTask::start`

```

**Comment by notgull** [comment] 2024-01-09 15:01
Duplicate of https://github.com/smol-rs/event-listener-strategy/issues/13

**Closed** 2024-01-09 15:01 UTC
